### ISSUE TITLE
Translate the result classification table

### ISSUE THREAD

**Issue by alexgcsa** [eubr-bigsea/citrus#107]
These tables that appear in the result of classification models should be completely translated to Portuguese (PT-BR):

![image](https://user-images.githubusercontent.com/24958541/54774915-8eff3b00-4beb-11e9-9b71-35c271015179.png)

Replace "F1" by "Medida F (F1)"
Replace "Weighted Precision" by "Precisão (Ponderada)"
Replace "Weighted Recall" by "Revocação (Ponderada)"
Replace "Accuracy" by "Acurácia"

**Comment by waltersf** [comment]
Fixed. Please, review it,

**Comment by alexgcsa** [comment]
Just testes on the[ icd](https://icd.ctweb.inweb.org.br) and the[ test](https://lemonade.ctweb.inweb.org.br) environments. It is still not corrected:

![image](https://user-images.githubusercontent.com/24958541/56870361-ad273a80-69e4-11e9-9bf7-cd2fcf85deae.png)

**Comment by waltersf** [comment]
Now fixed in test environment. Later I'll update icd environment.
